from . import vmf_grade
from . import res_company_ext
from . import hr_work_location_ext
from . import vmf_mrf
from . import vmf_candidate
from . import hr_employee_ext
from . import vmf_payroll
from . import vmf_travel
from . import vmf_exit
from . import vmf_performance
from . import vmf_grievance
from . import vmf_headcount
from . import vmf_learning
from . import vmf_talent
