from odoo import models, fields, api
from datetime import date


class VmfHeadcountSnapshot(models.Model):
    _name = 'vmf.headcount.snapshot'
    _description = 'Monthly Headcount Snapshot'
    _order = 'snapshot_date desc, company_id'
    _rec_name = 'name'

    name = fields.Char('Snapshot Reference', compute='_compute_name', store=True)
    snapshot_date = fields.Date('Snapshot Date', required=True)
    snapshot_month = fields.Char('Month / Year', compute='_compute_month', store=True)
    company_id = fields.Many2one('res.company', string='Company', required=True)

    # Headcount by category
    expat_permanent = fields.Integer('Expats Permanent')
    expat_contractual = fields.Integer('Expats Contractual')
    national_permanent = fields.Integer('National Permanent')
    national_contractual = fields.Integer('National Contractual')
    security_agency = fields.Integer('Security / Agency')
    total_headcount = fields.Integer('Total', compute='_compute_total', store=True)

    # Ratios
    expat_total = fields.Integer('Total Expats', compute='_compute_total', store=True)
    national_total = fields.Integer('Total Nationals', compute='_compute_total', store=True)
    expat_national_ratio = fields.Char('Expat:National Ratio', compute='_compute_total', store=True)

    # Prior month comparison
    prior_month_total = fields.Integer('Prior Month Total')
    variance = fields.Integer('Variance', compute='_compute_variance', store=True)
    variance_pct = fields.Float('Variance %', compute='_compute_variance', store=True)
    deviation_justification = fields.Text('Deviation Justification')

    generated_by = fields.Many2one('res.users', string='Generated By', default=lambda self: self.env.user)
    notes = fields.Text('Notes')

    @api.depends('company_id', 'snapshot_date')
    def _compute_name(self):
        for rec in self:
            co = rec.company_id.name if rec.company_id else ''
            dt = rec.snapshot_date.strftime('%b %Y') if rec.snapshot_date else ''
            rec.name = f"HC/{co}/{dt}"

    @api.depends('snapshot_date')
    def _compute_month(self):
        for rec in self:
            rec.snapshot_month = rec.snapshot_date.strftime('%B %Y') if rec.snapshot_date else ''

    @api.depends('expat_permanent', 'expat_contractual', 'national_permanent',
                 'national_contractual', 'security_agency')
    def _compute_total(self):
        for rec in self:
            rec.expat_total = rec.expat_permanent + rec.expat_contractual
            rec.national_total = rec.national_permanent + rec.national_contractual + rec.security_agency
            rec.total_headcount = rec.expat_total + rec.national_total
            if rec.national_total:
                ratio = rec.expat_total / rec.national_total
                rec.expat_national_ratio = f"{ratio:.2f}:1"
            else:
                rec.expat_national_ratio = "N/A"

    @api.depends('total_headcount', 'prior_month_total')
    def _compute_variance(self):
        for rec in self:
            rec.variance = rec.total_headcount - rec.prior_month_total
            if rec.prior_month_total:
                rec.variance_pct = (rec.variance / rec.prior_month_total) * 100
            else:
                rec.variance_pct = 0

    @api.model
    def generate_snapshot(self, snapshot_date=None, company_ids=None):
        """Auto-generate headcount snapshot from live employee data"""
        if not snapshot_date:
            snapshot_date = date.today().replace(day=1)

        if not company_ids:
            company_ids = self.env['res.company'].search([]).ids

        results = []
        for company_id in company_ids:
            emp_domain = [
                ('company_id', '=', company_id),
                ('active', '=', True),
            ]
            employees = self.env['hr.employee'].search(emp_domain)

            counts = {
                'expat_permanent': len(employees.filtered(lambda e: e.vmf_employee_category == 'expat_permanent')),
                'expat_contractual': len(employees.filtered(lambda e: e.vmf_employee_category == 'expat_contractual')),
                'national_permanent': len(employees.filtered(lambda e: e.vmf_employee_category == 'national_permanent')),
                'national_contractual': len(employees.filtered(lambda e: e.vmf_employee_category == 'national_contractual')),
                'security_agency': len(employees.filtered(lambda e: e.vmf_employee_category == 'security_agency')),
            }

            # Find prior month snapshot
            prior = self.search([
                ('company_id', '=', company_id),
                ('snapshot_date', '<', snapshot_date),
            ], order='snapshot_date desc', limit=1)

            snapshot = self.create({
                'snapshot_date': snapshot_date,
                'company_id': company_id,
                'prior_month_total': prior.total_headcount if prior else 0,
                **counts,
            })
            results.append(snapshot)
        return results
